file(SIZE "${ROM}" rom_size)
if(NOT rom_size EQUAL 4194304)
  message(FATAL_ERROR "Expected a 4 MiB HiROM, got ${rom_size} bytes")
endif()
file(READ "${ROM}" value OFFSET 0 LIMIT 4 HEX)
if(NOT value STREQUAL "00102030")
  message(FATAL_ERROR "Incorrect bank 0 lower-half contents: ${value}")
endif()
file(READ "${ROM}" value OFFSET 65536 LIMIT 4 HEX)
if(NOT value STREQUAL "01112131")
  message(FATAL_ERROR "Incorrect bank 1 contents: ${value}")
endif()
file(READ "${ROM}" value OFFSET 4128768 LIMIT 4 HEX)
if(NOT value STREQUAL "3f123456")
  message(FATAL_ERROR "Incorrect bank 63 contents: ${value}")
endif()
# The reset vector must point into ordinary code in bank 0's upper half.
file(READ "${ROM}" reset_hex OFFSET 65532 LIMIT 2 HEX)
string(SUBSTRING "${reset_hex}" 0 2 reset_low)
string(SUBSTRING "${reset_hex}" 2 2 reset_high)
math(EXPR reset "0x${reset_low} | (0x${reset_high} << 8)")
if(reset LESS 32768 OR reset GREATER 65455)
  message(FATAL_ERROR "Reset vector is outside bank 0 ordinary program ROM")
endif()
