file(SIZE "${ROM}" rom_size)
if(NOT rom_size EQUAL 262144)
  message(FATAL_ERROR "Expected a 256 KiB ROM, got ${rom_size} bytes")
endif()

file(READ "${ROM}" value OFFSET 65495 LIMIT 1 HEX)
if(NOT value STREQUAL "08")
  message(FATAL_ERROR "Incorrect ROM-size header byte: ${value}")
endif()
file(READ "${ROM}" value OFFSET 65493 LIMIT 1 HEX)
if(NOT value STREQUAL "21")
  message(FATAL_ERROR "Incorrect HiROM map-mode byte: ${value}")
endif()
file(READ "${ROM}" value OFFSET 0 LIMIT 4 HEX)
if(NOT value STREQUAL "01234567")
  message(FATAL_ERROR "Incorrect bank 0 contents: ${value}")
endif()
file(READ "${ROM}" value OFFSET 65536 LIMIT 4 HEX)
if(NOT value STREQUAL "11223344")
  message(FATAL_ERROR "Incorrect bank 1 contents: ${value}")
endif()
file(READ "${ROM}" value OFFSET 196608 LIMIT 4 HEX)
if(NOT value STREQUAL "aabbccdd")
  message(FATAL_ERROR "Incorrect bank 3 contents: ${value}")
endif()

set(CHECKSUM_OFFSET 65500)
set(CHECKSUM_OFFSET_PLUS_2 65502)
include("${CMAKE_CURRENT_LIST_DIR}/../snes-verify-checksum.cmake")
