# Verify the SNES checksum independently of the post-link utility.
file(READ "${ROM}" rom_hex HEX)
string(LENGTH "${rom_hex}" hex_length)
math(EXPR checksum_end "${hex_length} - 2")
set(sum 0)
foreach(offset RANGE 0 ${checksum_end} 2)
  string(SUBSTRING "${rom_hex}" ${offset} 2 byte)
  math(EXPR sum "(${sum} + 0x${byte}) & 0xffff")
endforeach()

file(READ "${ROM}" complement_hex OFFSET ${CHECKSUM_OFFSET} LIMIT 2 HEX)
file(READ "${ROM}" checksum_hex OFFSET ${CHECKSUM_OFFSET_PLUS_2} LIMIT 2 HEX)
string(SUBSTRING "${complement_hex}" 0 2 complement_low)
string(SUBSTRING "${complement_hex}" 2 2 complement_high)
string(SUBSTRING "${checksum_hex}" 0 2 checksum_low)
string(SUBSTRING "${checksum_hex}" 2 2 checksum_high)
math(EXPR complement "0x${complement_low} | (0x${complement_high} << 8)")
math(EXPR checksum "0x${checksum_low} | (0x${checksum_high} << 8)")
math(EXPR pair "${checksum} ^ ${complement}")
if(NOT pair EQUAL 65535)
  message(FATAL_ERROR "Checksum/complement pair is invalid")
endif()
if(NOT sum EQUAL checksum)
  message(FATAL_ERROR
    "Stored checksum ${checksum} does not match ROM byte sum ${sum}")
endif()
