#!/usr/bin/env python3
"""Generate the repetitive 4 MiB HiROM linker fragments."""

from pathlib import Path

BANK_COUNT = 64
HERE = Path(__file__).resolve().parent.parent

linker = ["/* Automatically generated by generate-banked-rom.py. */", "", "MEMORY {"]
for bank in range(1, BANK_COUNT):
    origin = (0xC0 + bank) << 16
    minimum_size = (bank + 1) * 64
    linker.append(
        f"  rom_bank{bank} (r) : ORIGIN = 0x{origin:06x}, "
        f"LENGTH = __rom_size >= {minimum_size} ? 0x10000 : 0"
    )
linker.extend(["}", "", "SECTIONS {"])
for bank in range(1, BANK_COUNT):
    linker.append(
        f"  .rom_bank{bank} : {{ KEEP(*(.rom_bank{bank} .rom_bank{bank}.*)) }} "
        f">rom_bank{bank}"
    )
linker.extend(["}", ""])
(HERE / "banked-rom.ld").write_text("\n".join(linker))

output = ["/* Automatically generated by generate-banked-rom.py. */"]
for bank in range(1, BANK_COUNT):
    output.append(f"FULL(rom_bank{bank})")
output.append("")
(HERE / "banked-output.ld").write_text("\n".join(output))
