file(SIZE "${ROM}" rom_size)
if(NOT rom_size EQUAL 4194304)
  message(FATAL_ERROR "Expected a 4 MiB LoROM, got ${rom_size} bytes")
endif()
file(READ "${ROM}" first_bank OFFSET 0 LIMIT 32768 HEX)
string(FIND "${first_bank}" "00102030" bank0_position)
if(bank0_position EQUAL -1)
  message(FATAL_ERROR "Bank 0 marker was not found in the first LoROM bank")
endif()
file(READ "${ROM}" value OFFSET 32768 LIMIT 4 HEX)
if(NOT value STREQUAL "01112131")
  message(FATAL_ERROR "Incorrect bank 1 contents: ${value}")
endif()
file(READ "${ROM}" value OFFSET 4128768 LIMIT 4 HEX)
if(NOT value STREQUAL "7e123456")
  message(FATAL_ERROR "Incorrect bank 126/$FE mirror contents: ${value}")
endif()
file(READ "${ROM}" value OFFSET 4161536 LIMIT 4 HEX)
if(NOT value STREQUAL "7f123456")
  message(FATAL_ERROR "Incorrect bank 127/$FF mirror contents: ${value}")
endif()
