file(SIZE "${ROM}" rom_size)
if(NOT rom_size EQUAL 131072)
  message(FATAL_ERROR "Expected a 128 KiB ROM, got ${rom_size} bytes")
endif()

file(READ "${ROM}" value OFFSET 32727 LIMIT 1 HEX)
if(NOT value STREQUAL "07")
  message(FATAL_ERROR "Incorrect ROM-size header byte: ${value}")
endif()
file(READ "${ROM}" value OFFSET 32725 LIMIT 1 HEX)
if(NOT value STREQUAL "20")
  message(FATAL_ERROR "Incorrect LoROM map-mode byte: ${value}")
endif()
file(READ "${ROM}" value OFFSET 32768 LIMIT 4 HEX)
if(NOT value STREQUAL "11223344")
  message(FATAL_ERROR "Incorrect bank 1 contents: ${value}")
endif()
file(READ "${ROM}" value OFFSET 98304 LIMIT 4 HEX)
if(NOT value STREQUAL "aabbccdd")
  message(FATAL_ERROR "Incorrect bank 3 contents: ${value}")
endif()

set(CHECKSUM_OFFSET 32732)
set(CHECKSUM_OFFSET_PLUS_2 32734)
include("${CMAKE_CURRENT_LIST_DIR}/../snes-verify-checksum.cmake")
